2020-08-17 10:10:23,950 ERROR: Exception on / [GET] [in /home/trunganh/AVTA/Work/code/FLASK_BLOG/myblog/venv/lib/python3.8/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/trunganh/AVTA/Work/code/FLASK_BLOG/myblog/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/trunganh/AVTA/Work/code/FLASK_BLOG/myblog/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/trunganh/AVTA/Work/code/FLASK_BLOG/myblog/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/trunganh/AVTA/Work/code/FLASK_BLOG/myblog/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/trunganh/AVTA/Work/code/FLASK_BLOG/myblog/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/trunganh/AVTA/Work/code/FLASK_BLOG/myblog/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/trunganh/AVTA/Work/code/FLASK_BLOG/myblog/venv/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/trunganh/AVTA/Work/code/FLASK_BLOG/myblog/app/routes.py", line 49, in index
    return render_template('index.html', title='Home Page', form=form, posts=posts.items,
  File "/home/trunganh/AVTA/Work/code/FLASK_BLOG/myblog/venv/lib/python3.8/site-packages/flask/templating.py", line 137, in render_template
    return _render(
  File "/home/trunganh/AVTA/Work/code/FLASK_BLOG/myblog/venv/lib/python3.8/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/trunganh/AVTA/Work/code/FLASK_BLOG/myblog/venv/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/trunganh/AVTA/Work/code/FLASK_BLOG/myblog/venv/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/trunganh/AVTA/Work/code/FLASK_BLOG/myblog/venv/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/trunganh/AVTA/Work/code/FLASK_BLOG/myblog/app/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/trunganh/AVTA/Work/code/FLASK_BLOG/myblog/venv/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/trunganh/AVTA/Work/code/FLASK_BLOG/myblog/venv/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "<unknown>", line 77, in template
jinja2.exceptions.TemplateSyntaxError: Missing end of comment tag
2020-08-17 10:10:24,408 ERROR: Exception on / [GET] [in /home/trunganh/AVTA/Work/code/FLASK_BLOG/myblog/venv/lib/python3.8/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/trunganh/AVTA/Work/code/FLASK_BLOG/myblog/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/trunganh/AVTA/Work/code/FLASK_BLOG/myblog/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/trunganh/AVTA/Work/code/FLASK_BLOG/myblog/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/trunganh/AVTA/Work/code/FLASK_BLOG/myblog/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/trunganh/AVTA/Work/code/FLASK_BLOG/myblog/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/trunganh/AVTA/Work/code/FLASK_BLOG/myblog/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/trunganh/AVTA/Work/code/FLASK_BLOG/myblog/venv/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/trunganh/AVTA/Work/code/FLASK_BLOG/myblog/app/routes.py", line 49, in index
    return render_template('index.html', title='Home Page', form=form, posts=posts.items,
  File "/home/trunganh/AVTA/Work/code/FLASK_BLOG/myblog/venv/lib/python3.8/site-packages/flask/templating.py", line 137, in render_template
    return _render(
  File "/home/trunganh/AVTA/Work/code/FLASK_BLOG/myblog/venv/lib/python3.8/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/trunganh/AVTA/Work/code/FLASK_BLOG/myblog/venv/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/trunganh/AVTA/Work/code/FLASK_BLOG/myblog/venv/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/trunganh/AVTA/Work/code/FLASK_BLOG/myblog/venv/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/trunganh/AVTA/Work/code/FLASK_BLOG/myblog/app/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/trunganh/AVTA/Work/code/FLASK_BLOG/myblog/venv/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/trunganh/AVTA/Work/code/FLASK_BLOG/myblog/venv/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "<unknown>", line 77, in template
jinja2.exceptions.TemplateSyntaxError: Missing end of comment tag
2020-08-17 10:10:24,622 ERROR: Exception on / [GET] [in /home/trunganh/AVTA/Work/code/FLASK_BLOG/myblog/venv/lib/python3.8/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/trunganh/AVTA/Work/code/FLASK_BLOG/myblog/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/trunganh/AVTA/Work/code/FLASK_BLOG/myblog/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/trunganh/AVTA/Work/code/FLASK_BLOG/myblog/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/trunganh/AVTA/Work/code/FLASK_BLOG/myblog/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/trunganh/AVTA/Work/code/FLASK_BLOG/myblog/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/trunganh/AVTA/Work/code/FLASK_BLOG/myblog/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/trunganh/AVTA/Work/code/FLASK_BLOG/myblog/venv/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/trunganh/AVTA/Work/code/FLASK_BLOG/myblog/app/routes.py", line 49, in index
    return render_template('index.html', title='Home Page', form=form, posts=posts.items,
  File "/home/trunganh/AVTA/Work/code/FLASK_BLOG/myblog/venv/lib/python3.8/site-packages/flask/templating.py", line 137, in render_template
    return _render(
  File "/home/trunganh/AVTA/Work/code/FLASK_BLOG/myblog/venv/lib/python3.8/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/trunganh/AVTA/Work/code/FLASK_BLOG/myblog/venv/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/trunganh/AVTA/Work/code/FLASK_BLOG/myblog/venv/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/trunganh/AVTA/Work/code/FLASK_BLOG/myblog/venv/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/trunganh/AVTA/Work/code/FLASK_BLOG/myblog/app/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/trunganh/AVTA/Work/code/FLASK_BLOG/myblog/venv/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/trunganh/AVTA/Work/code/FLASK_BLOG/myblog/venv/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "<unknown>", line 77, in template
jinja2.exceptions.TemplateSyntaxError: Missing end of comment tag
